export const ActionTypes = {

  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  DELETE_USERS_SUCCESS: "DELETE_USERS_SUCCESS",
  UPDATE_USERS_SUCCESS: "UPDATE_USERS_SUCCESS",
};
